name: "SonarQube Scanner"
description: "Static Analysis using SonarQube"
author: "Patrick Mennen <patrick.mennen@philips.com>"
branding:
  color: green
  icon: box

inputs:
  projectName:
    description: Application name
    required: true

  projectKey:
    description: Sonar Project Key
    required: true

  baseDir:
    description: Project Base Directory
    required: true
    default: .

  token:
    description: Sonar Login Token
    required: true

  url:
    description: Sonar Server url
    required: true
runs:
  using: docker
  image: Dockerfile
