name: 'SonarQube Scanner'
description: 'Static Analysis using SonarQube'
author: 'Patrick Mennen <patrick.mennen@philips.com>'
branding: box
color: green

inputs:
  projectName:
    description: Application name
    required: true

  projectKey:
    description: Sonar Project Key
    required: true

  baseDir:
    description: Project Base Directory
    required: true

  token:
    description: Sonar Login Token
    required: true

  url:
    description: Sonar Server url
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - node /github/workflow/sonar-scanner-action/dist/index.js
