name: "SonarQube Scanner"
description: "Static Analysis using SonarQube"
author: "Forest Keepers"
branding:
  icon: "activity"
  color: "green"

inputs:
  projectName:
    description: "Sonar Project name"
    required: true

  projectKey:
    description: "Sonar Project Key"
    required: true

  baseDir:
    description: "Project Base Directory"
    required: false
    default: "."

  token:
    description: "Sonar Login Token"
    required: true

  url:
    description: "Sonar Server url"
    required: true

  scmProvider:
    description: "SCM provider"
    required: false
    default: "git"

  sourceEncoding:
    description: "Encoding of the source files"
    required: false
    default: "UTF-8"

  sonarCommand:
    required: false
    default: "sonar-scanner"

  enablePullRequestDecoration:
    description: "Decorate a pull request. PR, branch and base are extracted from the pull request event"
    required: false

runs:
  using: docker
  image: Dockerfile
