name: "build-test"
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container: philipssoftware/sonar-scanner:4.3

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test
      - name: Build distribution
        run: yarn build
      - name: Check dist is up to date
        run: |
          changes=$(git status -s --porcelain --untracked-files=no | wc -l)
          [ $changes -gt 0 ] && exit 1
